# Site settings
title: My Name is Trevor
email: ampleheights@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Asheville UI/UX Graphic design and illustration.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.mynameistrevor.com" # the base hostname & protocol for your site
twitter_username: ampleheights
github_username:  treall

# Build settings
markdown: kramdown

port: 8080
highlighter: true
