# Site settings
title: My Name is Trevor
email: ampleheights@gmail.com
description: "Asheville UI/UX, Graphic design and illustration."
#> # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.mynameistrevor.com" # the base hostname & protocol for your site
twitter_username: trevoristall
github_username:  trevoristall

#exclude: [scripts/]
#source: doc/
#destination: app/

# Build settings
markdown: kramdown

port: 8080
highlighter: true
